name: Build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build site
      run: npm run build
      env:
        CI: 'false'
    - name: Push to Github
      run: |
        cp -r build/. ${{ runner.temp }}/build
        git fetch origin
        git switch -f build
        rm -r *
        cp -r ${{ runner.temp }}/build/. .
        git config user.name 'Sion'
        git config user.email 'atlasacademy-sion@users.noreply.github.com'
        git add --all
        git commit -m "Build ${{ github.sha }}"
        git push -f origin
